# This file was generated by GoReleaser. DO NOT EDIT.
cask "fft" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "216e20e712bbf24c7c879a35c52aef23afceda75528877d5241f2113285a4ce0"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1e47f7b3e055aa16ee5c218b3e072246c52b680963a9da42076c2696cf3f655"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "836af9ba2d623c07489b0c76b0440e88307ff463dd04ed70028510eb369682a0"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1a60826f2cfb76e34b6dc844b01c4d4ce7e671c9977bad9d5a76288c20a2c4e"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fft"
  desc "A CLI for the fulfillmenttools API — every operation reachable from your shell."
  homepage "https://github.com/Joessst-Dev/fft-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fft"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fft"]
    end
  end

  # No zap stanza required

end
