# This file was generated by GoReleaser. DO NOT EDIT.
cask "fft" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9cf86cdbcd28bbeb719994463bad634a8aac4c3315a6a4b00cdf945a12ee19b0"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a81b535f6897f5c8ea203aff3266beefae2482985930d710c758ef7398dd58d4"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "75e6ec2d519b97f960ff495ebd4eb9b2891f04bb90e080126b3518fa6c5c3f0f"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ac4d558b73868af32da9bc7932a3ec3c5629118715ef9b0b455a07d551decdf"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fft"
  desc "A CLI for the fulfillmenttools API — every operation reachable from your shell."
  homepage "https://github.com/Joessst-Dev/fft-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fft"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fft"]
    end
  end

  # No zap stanza required

end
