# This file was generated by GoReleaser. DO NOT EDIT.
cask "fft" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c0a9bb4a75a1eded60ac002f8f36fb7b6b5027eacc40f9f50438f86288624a0c"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d42a949ad509d70046556c24ad95143b53c382f55b6e27a641b75a5c5c977b5"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7dbc256a1edd1cf2029e56b68a7aece93db146107d19fa598dc82eee8f95cd28"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bff261f02314ef5ace059fd8f20a9d99e6c3fc7f5855a5021b27774d57e5903f"
      url "https://github.com/Joessst-Dev/fft-cli/releases/download/v#{version}/fft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fft"
  desc "A CLI for the fulfillmenttools API — every operation reachable from your shell."
  homepage "https://github.com/Joessst-Dev/fft-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fft"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fft"]
    end
  end

  # No zap stanza required

end
